name: Dev-Deployment
on:
  # Runs on the push to the develop branch
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: http://localhost:4000
    steps:
      - uses: actions/checkout@v2
      # setup the node development environment
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install all dependencies
        run: npm install
      # to added after the merge of test PR
      - name: Run tests and generate coverage
        run: npm run coverage -- -u
      - name: Check linting errors
        run: npm run lint
      - name: Run the build and check success
        run: npm run build
  deploy:
    # deploy to heroku dev pipeline
    concurrency:
      group: heroku_deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment: development
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: '${{secrets.HEROKU_EMAIL}}'
