name: review-app-destroy
on:
  pull_request:
    types:
      - closed

# SEE: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  pull-requests: write

# Update these variables for your project
env:
  HEROKU_PIPELINE_NAME: devpulse

jobs:
  # Destroys the PR's Review App on Heroku
  heroku_review_app_destroy:
    name: Destroy Heroku Review App
    runs-on: ubuntu-latest
    steps:
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true

      - name: Set Heroku Review App name
        run: echo HEROKU_APP_NAME="${{ env.HEROKU_PIPELINE_NAME }}-review-app-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Get Heroku Review App info
        id: heroku_apps_info
        continue-on-error: true
        run: heroku apps:info -a ${{ env.HEROKU_APP_NAME }}

      - name: Set exists ENV vars
        run: |
          echo HEROKU_APP_EXISTS="${{ steps.heroku_apps_info.outcome == 'success' }}" >> $GITHUB_ENV

      - name: Destroy Heroku Review App
        if: env.HEROKU_APP_EXISTS == 'true'
        run: heroku apps:destroy --app=${{ env.HEROKU_APP_NAME }} --confirm=${{ env.HEROKU_APP_NAME }}

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v1
        if: env.HEROKU_APP_EXISTS == 'true'
        with:
          message: ":warning: The Heroku Review App **${{ env.HEROKU_APP_NAME }}** has been destroyed."
          GITHUB_TOKEN: ${{ github.token }}